### ISSUE TITLE
Macros in user space

### ISSUE THREAD

**Issue by borkdude** [borkdude/cherry#4]
Macros need to run in the same environment as the transpiler. Therefore it makes sense to force users to declare macros in separate `.cljc` files: `.cljc` so the cherry transpiler can run in both clojure/bb and JS environments.

Say we have `foo.cljs` which compiles to `foo.mjs` but requires a macro from `bar.cljc`, how would we declare that?

```
(ns foo (:require-macros ["./bar.cljc" :refer [my-macro]]))

(my-macro ...)
``` 

Or we can make the choice that macros are also transpiled functions and cherry only runs in JS. Then you could even write macros in JavaScript... I'm actually leaning towards that now.

Similar to what bun.js does: https://twitter.com/jarredsumner/status/1493204320984047619

We should explore both options.

## Interpreter approach

The interpreter approach needs you to hold deps on the "classpath" when you want to use macros from another library, since macros would be elided in .mjs output.

## Transpiled macros approach

...

**Comment by aleedmanath** [comment]
it'd be beneficial to have macro-expansion happen in same language as runtime so you can take full advantage of power of macros - e.g. using `bindings` for contextual state 

i've run into limitations of this when writing a custom Hiccup compiler / React wrapper. I was trying to compose macros inside a component, each bound to a bound context by parent macro (`defc`), but if quoting any expressions or leaving them unevaluated they'd run in JS, so I had to manually eval/macroexpand the nested macro (e.g. `css` macro for compiling styles)

the only concern to the only-JS approach would be bundle size, as macros are often used to remove code you don't want included in final bundle. but it looks like tweet you linked mentions dead code elimination, so that is already a consideration

**Comment by borkdude** [comment]
Macros in Clojure are ran inside the compiler. The JS environment of the compiler doesn't need to be the same environment as the JS target environment (but it can be). The macro function itself isn't visible in the output JS. If you need macros at runtime, this is imo a sign that you just needed to write a function in the first place.

**Comment by aleedmanath** [comment]
> If you need macros at runtime, this is imo a sign that you just needed to write a function in the first place.

Now that I think about it.. I didn't need them at runtime since 1/ I wanted the transpiles to take place while compiling, not every time a component was rendered 2/ I did not want transpile logic included in bundle 

So you may be right, it wasn't a CLJS-CLJ macro issue but just general dynamic of working with browser code. Sorry for the detour here 😅

**Comment by borkdude** [comment]
So, this is what macros ran by the compiler in JS might look like. `macros.cljs` is first compiled to `macros.mjs`. Then `macros.mjs` is required with `:require-macros` from `macro_usage.cljs`. The compiler loads the (already compiled) macro code before it traverses the whole file, so it has the macros available for execution.

<img width="727" alt="Screenshot 2022-08-01 at 13 04 53" src="https://user-images.githubusercontent.com/284934/182135253-1141a2a2-8ca0-4740-a519-858e85323966.png">

**Comment by borkdude** [comment]
Part 1 is now complete with the transpiler approach. See examples/react.
